name: KICS Vulnerability Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kics_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run KICS Scan
        uses: Checkmarx/kics-github-action@v1.6
        with:
          path: '.'
          output_path: 'kics-results'
          output_formats: 'json,sarif,html'

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kics-results/results.sarif

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: kics-html-report
          path: kics-results/results.html
